name: Arduino CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: Setup Arduino Core
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn arduino:avr:uno ./ssmmaws_project
