name: Build ESP32 Sketch with Cache

on:
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Cache Arduino CLI core and config files
    - name: Cache Arduino CLI folder
      uses: actions/cache@v3
      with:
        path: ~/.arduino15
        key: ${{ runner.os }}-arduino15-${{ hashFiles('**/*.ino') }}
        restore-keys: |
          ${{ runner.os }}-arduino15-

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: Configure Arduino CLI
      run: |
        arduino-cli config init --overwrite
        arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

    - name: Install ESP32 Core (if missing)
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@3.3.0 || echo "Core already installed"

    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 .
